### ISSUE TITLE
profile picture issues for linkedin, gmail, and outlook

### ISSUE THREAD

**Issue by abhiram040** [pdc-uottawa/PDCwebsite#28]
When, the user signs in to Linkedin, appropriate picture is not displayed. The display features of outlook and google need to be tested and fixed.

**Comment by HarmanBhutani** [comment]
We checked it quite briefly and found that the image is coming when the user is signing in with Linkedin or Gmail but the strange thing is the same code does not work for outlook and only the user's initial name comes in place of the image. Outlook API is not returning the image of the student and it may be because of images uploading to uottawa server.
